### ISSUE TITLE
White background issue

### ISSUE THREAD

**Issue by CyberStudioUnited** [josephcrosmanplays532/Vyond-Legacy-Offline#1]
**Describe the bug**
a bug where the scene dosent load

**To Reproduce**
1. launch the lvm
2. Click on Make a video
3. See error

**Expected behavior**
Expected for the scene to load.

**Screenshots**
![here](https://user-images.githubusercontent.com/72953518/153529014-751baa2e-3d6b-4202-b953-657593f6e930.PNG)

**Comment by josephcrosmanplays532** [comment]
that has been fixed now in the settings.bat file.
